### ISSUE TITLE
Créer - éditer une personne (personne)

### ISSUE THREAD

**Issue by bouviermullerp** [data-players/passerelle_normandie#2]
En tant qu'utilisateur anonyme, je peux créer un profil afin de pouvoir être visible sur la plateforme et créer des concepts (organisations, lieux et événements).

Lorsque je crée un compte sur la plateforme, je crée mon profil avec mes informations de contact.

Les informations obligatoires sont : 
- Prénom
- Nom
- Mail

Les informations optionnelles sont : 
- Code postal
- Photo
- Présentation
- Organisations
  - si l'organisation n'existe pas déjà, alors il faudra sauvegarder son profil, créer l'organisation, puis revenir éditer son profil) - lié à data-players/Passerelle-Normandi#8 
  - On spécifiera à ce moment son rôle : utilisateur (adhérent, client, etc.) ; contributeur (bénévole, partenaire, salarié)
- Lieux (même chose que pour les organisations) - lié à data-players/Passerelle-Normandi#9 
- Numéro de tel
- Profil LinkedIn
- Profil Fb
- Profil Mastodon
- Site web

**A clarifier**:
- Compétences (via un système d'autocompletion avec la possibilité de proposer une nouvelle compétence => modération requise par l'équipe de PN pour la cohérence de la taxonomie) => lié à data-players/Passerelle-Normandi#18 

Ontologie ? 
FOAF http://xmlns.com/foaf/spec/

**Comment by bouviermullerp** [comment]
@simonLouvet je remet cette carte en dev car elle ne respecte pas les spec (surement pour de bonnes raisons, mais alors il faut modifier la spec ou documenter pour être raccord :) )

**Comment by simonLouvet** [comment]
ajout du numéro de téléphone dans l'ontologie demandée : https://github.com/assemblee-virtuelle/pair/issues/149

**Comment by simonLouvet** [comment]
demande d'ajout des profils dans l'ontologie
https://github.com/assemblee-virtuelle/pair/issues/152
