### ISSUE TITLE
Affichage d'une photo pour une organisation

### ISSUE THREAD

**Issue by ilouboff** [data-players/passerelle_normandie#29]
Le système ne semble pas supporter l'ajout de photo. Ca fonctionne bien pour des logos mais pas pour des images, or un certain nombre d'organisations n'auront pas de logo à proprement parler. Ca serait top si on pouvait également mettre une photo en l'absence de logo.

**Comment by bouviermullerp** [comment]
@simonLouvet y a-t-il une taille maximum des photos qu'on peut mettre en ligne ? J'ai essayé un JPEG de 132 Ko sur l'organisation "Pôle de Santé de Putanges-Pont-Ecrepin" et ça ne se met pas en ligne.

**Comment by simonLouvet** [comment]
Il semble que la qualité des images uploadé dépend de la qualité du réseau. Trouver pourquois.
