### ISSUE TITLE
Créer une organisation

### ISSUE THREAD

**Issue by bouviermullerp** [data-players/passerelle_normandie#3]
En tant qu'utilisateur connecté, je peux créer une organisation.

Je peux soit créer une organisation en partant de rien, soit créer une organisation référencées sur autre serveur.

Les informations obligatoires sont : 
- Le nom de l'organisation

Les informations optionnelles sont : 
- Sa localisation (siège social) - adresse exacte - n° de la voie, voie, code postale et ville.
- Email
- Un ou plusieurs modérateurs (comportement à préciser)
- Présentation
- Site web
- Téléphone
- Photo

Les informations optionnelles et thématiques à renseigner si l'utilisateur choisit de référencer son organisation sur un moteur de recherche thématique : 

- Pour l'agriculture
- Pour la santé
- Pour les tiers-lieux

**Comment by simonLouvet** [comment]
il manque un numéro de téléphone dans l'ontologie
https://github.com/assemblee-virtuelle/pair/issues/149
