### ISSUE TITLE
Design Univers Tiers-lieux (2)

### ISSUE THREAD

**Issue by ilouboff** [data-players/passerelle_normandie#36]
Proposition de design pour la page organisation (à discuter si problématique...)

**Eléments transversaux (visibles peu importe l'onglet) :** 

- Photo en bandeau (avec un picto indiquant que l'on se trouve sur une page "organisation")
- Nom de l'organisation et logo
- Pictos de réseau sociaux avec les liens renseignés par l'organisation

**Eléments spécifiques à chaque onglet:**

//A propos : 
- Description
-  Section localisation (département, adresse et carte)
- Section contact (avec mail, téléphone et site web)

//Communauté : 
- Une section équipe
- Une section membres

// Projets : 
- Liste des projets portés par l'organisation ou sur lesquels elle est partenaire (nom du projet, photo et description)

// Evénements
- Liste des événements organisés par l'organisation ou sur lesquels elle est partenaire (nom de l'événement, date, description, liste des organisateurs, liste des partenaires)

// Média : 
- Galerie déroulante de vidéos
- Galerie déroulante de photos

// Lieux : 
- Liste des lieux gérés par l'organisation (nom du lieu, photo, description, localisation (ville, département), catérogorisation thématique le cas échéant (ex : tiers-lieu, ferme, centre de santé) 

[Page organisation v2.pdf](https://github.com/data-players/passerelle_normandie/files/5695842/Page.organisation.v2.pdf)

@bouviermullerp : effectivement, tu as raison... Le concept de lieu doit bien être distingué de celui d'organisation. J'ai adapté le doc du coup. Est-ce que tu peux me dire si ça te semble prêt pour être soumis à Simon? Thanks!

**Comment by bouviermullerp** [comment]
c'est top @ilouboff ! merci :) 

2 remarques : 
- Une interrogation concernant la place de "media" et "projets" au même niveau que les concepts "fondateurs" - j'ai l'impression que ça s'inserrerait plus logiquement dans le "a propos".
Les éléments qui sont décrits dans les concepts communauté (personne), (evenement) et lieu sont navigables, ils font références à d'autres concepts et forment le réseau, alors que Media, non.

- Je m'interroge aussi sur "projets". Est-ce que c'est un concept spécifique au tiers-lieu ? Il ne fait pas partie des 4 concepts fondamentaux (Acteurs, Orga, Lieux, Evenements) du départ. Ce n'est pas un problème du tout, mais je préfère qu'on soit bien explicite si on modifie la spec de départ.

**Comment by ilouboff** [comment]
Merci @bouviermullerp !

A nouveau, très bonnes remarques! :) 

Sur le premier point, je peux retirer média et on peut intégrer les galeries sous les briques de description, de localisation et de contact. Ca pourrait même être plus sympa d'avoir les photos et vidéos direct sur l'onglet "à propos". 

Sur le deuxième point, j'ai effectivement rajouté "projet" de nulle part sans l'expliciter. J'ai vu que le concept était déjà présent dans PAIR et plus on avance, plus il me semblerait pertinent de l'intégrer (parmi les concepts fondamentaux). Donc je vais créer une issue pour spéficier tout ça (ou updater une issue existante). Par contre, je l'imagine bien en onglet séparé (plutôt qu'intégré dans l'onglet à propos).
