### ISSUE TITLE
Créer un lieu

### ISSUE THREAD

**Issue by bouviermullerp** [data-players/passerelle_normandie#4]
En tant qu'utilisateur connecté, je peux créer un lieu

Les informations obligatoires sont : 
- Nom du lieu
- Adresse

Les informations optionnelles sont : 
- Horaires d'ouverture
- Matériel à disposition 
- Contact
- Site web

**Comment by bouviermullerp** [comment]
@simonLouvet je remet cette carte en dev car elle ne respecte pas les spec (surement pour de bonnes raisons, mais alors il faut modifier la spec ou documenter pour être raccord :) )

**Comment by simonLouvet** [comment]
@bouviermullerp ok, j'ai surtout tenté de mettre en place la notion devenement. Ja vais essayé de rajouter ce qu'il maque pour mardi pour le 8 ou avant

**Comment by simonLouvet** [comment]
champ non indispensable pour passer en test :
- Horaires d'ouverture
- Matériel à disposition

**Comment by simonLouvet** [comment]
demande d'ajout d'horaire d'ouverture dans l’ontologie : https://github.com/assemblee-virtuelle/pair/issues/150

**Comment by simonLouvet** [comment]
demande d'ajout du matériel dans l'ontologie : https://github.com/assemblee-virtuelle/pair/issues/151

**Comment by bouviermullerp** [comment]
This issue is closed,  #50 and #51 has been created in order to store issue for horaire ouverture and matériel.
