### ISSUE TITLE
Organiser un atelier de design pendant la résidence

### ISSUE THREAD

**Issue by ilouboff** [data-players/passerelle_normandie#40]
- [x] Igor fourni la liste des participants potentiels
- [x] Pierre contacte quelques personnes pour connaitre leur intérêt et leur présence potentiel
- [x] Définir une date
- [x] Organiser l'atelier
- [x] Apéro

Voilà la liste : https://docs.google.com/spreadsheets/d/1HpTujDDh5ea09ePmUsZ85OE-802swGuxwPnikf0YDKM/edit?usp=sharing

Il manque quelques mails, je complète asap.

1ère colonne : les personnes qu'on connait bien et que ça n'embêtera probablement pas de tester quelque chose en début de course.
2e colonne : les personnes qui pourraient être dans le coin début janvier.
3e colonne : les personnes qu'on connait moins ou qu'il serait plus judicieux de mobiliser quand le proto sera un peu plus avancé.
Toutes les personnes listées sont adhérentes de l'association el capitan.

**Comment by bouviermullerp** [comment]
Merci @ilouboff - je m'en occupe et prend contact avec quelqu'un.e.s que je ne connais pas. 
J'ai reformulé pour qu'elle soit un peu plus large

**Comment by bouviermullerp** [comment]
Il y a des "m" dans la colonne B, et je ne suis pas sur de savoir à quoi ça correspond :)
