### ISSUE TITLE
Créer un évènement

### ISSUE THREAD

**Issue by bouviermullerp** [data-players/passerelle_normandie#5]
En tant qu'utilisateur connecté,

Je peux créer un évènement.

Informations obligatoires : 
- Nom de l'évènement 
- Date, heure de début, heure de fin 
- Lieu 
- Description 

Informations optionnelles : 
- Reservation

Ontologie :
EVENT : http://motools.sourceforge.net/event/event.html

**Comment by simonLouvet** [comment]
Besoin de spécification pour reservation
