### ISSUE TITLE
Modifications affichage page organisation

### ISSUE THREAD

**Issue by ilouboff** [data-players/passerelle_normandie#63]
Affichage des membres : ne pas faire apparaître les titres si n<1.

Affichage de la carte : afficher dans la colonne de droite (tout en haut).

Affichage des informations générales (adresse, site, email, tel) : mettre ces informations sur la colonne de droite (faire apparaître sous la carte).

Affichage des lieux : faire apparaître sous les membres.

Affichage d'une vidéo : rajouter un champ pour insérer une vidéo sous le texte général de l'organisation.

**Comment by simonLouvet** [comment]
carte = la carte avec le marqueur de l'orga

**Comment by simonLouvet** [comment]
affichage de la vidéo : traité par #71
