### ISSUE TITLE
Pouvoir préciser le rôle qu'on a dans une orga à partir de son profil

### ISSUE THREAD

**Issue by ilouboff** [data-players/passerelle_normandie#67]
Pour l'instant, une personne peut seulement renseigner qu'elle est membre d'une organisation, sans pour autant indiquer son rôle.

Il faudrait donc deux champs permettant d'indiquer : 

Membre de l'équipe (salarié.e, bénévole, sociétaire) de : 

[champ d'autocompletion allant chercher la liste des organisations référencées]

Membre du réseau (adhérent.e, client.e, usager) de : 

[champ d'autocompletion allant chercher la liste des organisations référencées]

**Comment by simonLouvet** [comment]
same as #61
