### ISSUE TITLE
Organisation atelier restitution

### ISSUE THREAD

**Issue by ilouboff** [data-players/passerelle_normandie#84]
On essaye de caler ça le jeudi 24 dans l'aprem?

**Comment by bouviermullerp** [comment]
On est en COPIL Prats de 14 à 16 avec Simon après 16h ça pourra le faire !

**Comment by ilouboff** [comment]
Voilà le mail que je propose d'envoyer, ça t'irait?

****************************

Salut tout le monde,

Après un an de travail avec l'équipe de Dataplayers et de l'Assemblée Virtuelle, la plateforme de Passerelle Normandie est quasiment prête! Cette plateforme vise notamment à cartographier les projets inspirants des territoires normands et à favoriser la mise en relation de ces acteurs.

On vise un lancement officiel à la rentrée. D'ici-là, on souhaiterait présenter l'outil aux copains, recueillir vos premiers retours et profiter de l'été pour réaliser les ajustements qui ressortiront et gérer les bugs probables qu'on découvrira au cours des premières semaines d'utilisation.

Pour celles et ceux qui seraient dispo et motivé.e.s pour participer à ce petit temps de présentation et de test, on vous propose un petit goûter/atelier le jeudi 24 juin à 16h30 (ça se transformera très probablement en apéro dans la foulée...). Au programme : on vous lâche devant la bête et on recueille vos retours et impressions.

N'hésitez pas à nous confirmer votre présence, et si ça vous intéresse mais que vous n'êtes pas dispo sur ce créneau, aucun souci pour prévoir une session de rattrapage.

Merci d'avance pour vos réponses!

Igor
