### ISSUE TITLE
faire remonter à guillaume le besoin de desrcription sur le sector

### ISSUE THREAD

**Issue by simonLouvet** [data-players/passerelle_normandie#87]

**Comment by GuillaumeAV** [comment]
Quel est l'enjeu de cette issue @simonLouvet ?

**Comment by simonLouvet** [comment]
Coucou Guillaume, en lisant l'ontologie, nous avons pu constaté que les décors n'ont pas de description. Des ergonomies comme celle de coloris ou passerelle permettent de naviguer sur une thématique ou un sector pour voir tous les éléments (orga, personnes...) qui y sont liés. Igor aimerait que il y ai un texte de présentation lors ce que le user navigue sur le sector en plus des éléments lié. Je me demande également a quel point le sector ne pourrait avoir tous les autres attribut d'un sujet.

**Comment by GuillaumeAV** [comment]
Aaah ok ! 

Oui en effet ça pourrait être pertinent ! 

Au passage, mais ce n'est pas le sujet, on a complété les définitions des concepts de l'ontologie [dans ce doc :](https://docs.google.com/spreadsheets/d/1PMAB6WCNzRUrmxLwNvdSYrrrVESIwIP1QXT5FSwMS8g/edit?usp=sharing)

Je fais remonter ça à Thomas ! Vous en avez besoin rapidement ? 
La bise !

**Comment by GuillaumeAV** [comment]
Autre solution, il y a une classe enjeu

**Comment by simonLouvet** [comment]
La plateforme doit sortir fin Juillet donc nous en aurions besoin maintenant :-/

**Comment by GuillaumeAV** [comment]
Oups je l'avais fermée sans faire exprès ! Ok j'appelle Thomas !
